version: '2'
services:
  nginx:
    image: phalconphp/nginx
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
    links:
      -  app:php

  app:
    image: phalconphp/php-fpm:7-min
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    links:
      - mysql:mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_12345
      - MYSQL_DATABASE=app_db
    volumes:
      - ./stack/mysql/data:/var/lib/mysql:rw
      - ./stack/mysql/entrypoint:/docker-entrypoint-initdb.d
